diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=oulaya.omar@gmail.com
user.name=Oulaya omar
core.longpaths=true
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
alias.ls=log --graph --pretty=format:%C(yellow)%h\ %C(green)%ad%C(red)%d\ %C(reset)%s\ %C(blue)[%an] --decorate --date=short
alias.lg=log --graph --date=relative --pretty=tformat:'%C(red)%h%C(reset) -%C(auto)%d%Creset %s %C(green)(%an %ad)%C(reset)'
alias.ll=log --name-status --summary
alias.st=status
alias.ci=commit
alias.co=checkout
alias.cp=cherry-pick
alias.ignore=update-index --assume-unchanged
alias.stop-ignore=update-index --no-assume-unchanged
alias.update-remote=remote prune origin
alias.update-tags=fetch --prune origin +refs/tags/*:refs/tags/*
alias.pushf=push --force-with-lease
alias.pushfn=push --force-with-lease --no-verify
alias.pushn=push --no-verify
alias.pushr=push --set-upstream origin HEAD
alias.pushrf=push --force-with-lease --set-upstream origin HEAD
alias.pushrn=push --set-upstream origin HEAD --no-verify
alias.pushrfn=push --force-with-lease --set-upstream origin HEAD --no-verify
alias.pullr=pull origin HEAD
alias.oops=commit --amend --no-edit
branch.autosetupmerge=true
core.precomposeunicode=false
core.whitespace=-trailing-space
core.editor=code --wait
core.ignorecase=false
color.ui=auto
color.status.untracked=white red bold
credential.helper=osxkeychain
difftool.prompt=false
difftool.sourcetree.cmd=opendiff "$LOCAL" "$REMOTE"
difftool.sourcetree.path=
http.postbuffer=157286400
merge.ff=true
mergetool.sourcetree.cmd=/Applications/Sourcetree.app/Contents/Resources/opendiff-w.sh "$LOCAL" "$REMOTE" -ancestor "$BASE" -merge "$MERGED"
mergetool.sourcetree.trustexitcode=true
pull.rebase=true
push.default=simple
rerere.autoupdate=true
rerere.enabled=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
user.name=omar
